### ISSUE TITLE
gps per wavelength

### ISSUE THREAD

**Issue by hoyekan** [JanThorbecke/OpenSource#18]
Hello Prof., this is actually not an issue, but more of a question. I noticed that whenever I run the "fdelmodc" code, it always uses 5 points per wavelength for the dispersion calculation. What can I do to make the code use 10 points instead?

**Comment by JanThorbecke** [comment]
You can decrease the spatial grid by a factor of 2 to get 5 points per wavelength. The dispersion calculation is carried out to check if the modeling will remain stable and without (visible) distortion. This stability demands to use at least 5 points per wavelength, but you can always use more points per wavelenght by decreasing dx=dz to smaller values. Due to this decrease in dx usually dt must also be adjusted to smaller values to remain stable and distortion free. 
See for example Table 1 in "Dispersion Analysis of Numerical Wave Propagation
and Its Computational Consequences", Alain Sei and William Symes, Journal of Scientific Computing, Vok 10, No. 1, 1995

**Comment by hoyekan** [comment]
Thank you, Prof.
